formula ::= '=' scalar

scalar  ::= '-'? DIGITS ( '.' DIGITS )?
          | STRING
          | BOOL
          | NULL
          | path
          | fn_call

fn_call ::= UNARY     '(' scalar ')'
          | BINARY    '(' scalar ','  scalar ')'
          | MIXED     '(' scalar ','  tensor ')'
          | AGGREGATE '(' tensor ')'

tensor  ::= path

path    ::= ( '.'? '.' )? ( ( '/' | '\' ) ( DIGITS | LABEL | '*' | '.' '.' ) )+
